FROM registry.fedoraproject.org/fedora:26

COPY requirements.sh /root/requirements.sh

# reason for sync: https://github.com/container-images/container-image-template/pull/10#issuecomment-336403824
# and https://giphy.com/gifs/wat-loop-old-woman-jA8TT03Sj2pXO
RUN chmod a+x /root/requirements.sh && \
    sync && \
    exec /root/requirements.sh

VOLUME /src
WORKDIR /src
# we don't need to create an unprivileged user for the test run
# since we have complete access to docker socket = root on host
ENTRYPOINT ["make", "test"]
