FROM fedora:26

ADD requirements.sh /root/requirements.sh

RUN bash /root/requirements.sh

VOLUME /src
WORKDIR /src
# we don't need to create an unprivileged user for the test run
# since we have complete access to docker socket = root on host
ENTRYPOINT ["make", "test"]
