#!/bin/bash -ex

make doc
# A hack: we need Dockerhub to see a `Dockerfile` when cloning,
# but `Dockerfile` is actually a template and `make` will output
# `Dockerfile.rendered`. To make sure the build doesn't use
# the template, we replace it with the rendered `Dockerfile`
# after rendering. 
mv Dockerfile Dockerfile.template
