.TH "Fedora " "1" " Container Image Pages" "MAINTAINER" "DATE" 
.nh
.ad l


.SH NAME
.PP
myawesomeimage \- This is a simple container that just tells you how awesome it is. That's it.


.SH DESCRIPTION
.PP
Describe how image is used (user app, service, base image, builder image, etc.), the services or features it provides, and environment it is intended to run in (stand\-alone docker, atomic super\-privileged, oc multi\-container app, etc.).


.SH USAGE
.PP
Describe how to run the image as a container and what factors might influence the behavior of the image itself. Provide specific command lines that are appropriate for how the container should be run. Here is an example for a container image meant to be run by the atomic command:

.PP
To pull the container and set up the host system for use by the XYZ container, run:

.PP
.RS

.nf
# atomic install XYZimage

.fi
.RE

.PP
To run the XYZ container (after it is installed), run:

.PP
.RS

.nf
# atomic run XYZimage

.fi
.RE

.PP
To remove the XYZ container (not the image) from your system, run:

.PP
.RS

.nf
# atomic uninstall XYZimage

.fi
.RE

.PP
Also, describe default configuration options (when defined): hostname, domainname, user ID run as, exposed ports, volumes, working directory, command run by default, etc.

.PP
Some Fedora specific help


.SH ENVIRONMENT VARIABLES
.PP
Explain all environment variables available to run the image in different ways without the need of rebuilding the image. Change variables on the docker command line with \-e option. For example:

.PP
MYSQL\_PASSWORD=mypass
                The password set for the current MySQL user.


.SH LABELS
.PP
Describe LABEL settings (from the Dockerfile that created the image) that contains pertinent information.
For containers run by atomic, that could include INSTALL, RUN, UNINSTALL, and UPDATE LABELS. Others could
include BZComponent, Name, Version, Release, and Architecture. This section is optional.


.SH SECURITY IMPLICATIONS
.PP
If you expose ports or run with privileges, note those and provide an explanation. For example:

.PP
\-d
    Runs continuously as a daemon process in the background

.PP
\-p 9000:9000
    Opens  container  port  9000  and  maps it to the same port on the Host.


.SH HISTORY
.PP
Similar to a Changelog of sorts which can be as detailed as the maintainer wishes.


.SH SEE ALSO
.PP
Does Red Hat provide MariaDB technical support on RHEL 7? 
\[la]https://access.redhat.com/solutions/1247193\[ra]
Install and Deploy a Mariadb Container Image 
\[la]https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/single/getting-started-guide/#install_and_deploy_a_mariadb_container\[ra]
